### ISSUE TITLE
after updating to latest version of HA getting login error

### ISSUE THREAD

**Issue by sebking1971** [mitch-dc/volkswagen_we_connect_id#143]
ogger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47 
Integration: Volkswagen We Connect ID 
First occurred: 16:30:49 (1 occurrences) 
Last logged: 16:30:49

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth
    raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions

**Comment by sm4upt** [comment]
I get same error i logged in to myvolkswagen.de as mentioned in message it dosen't solve the problem

**Comment by sebking1971** [comment]
App was updated today so wonder if they did something to the login again.

Sebastian King | ***@***.*** | +44 7711 702100
________________________________

**Comment by DarkFox** [comment]
I restored HA to 2023.2.3 and still had the issue. Going to myvolkswagen.de and accepting all the terms on my account, seems to have fixed it for me.

**Comment by sm4upt** [comment]
logged in to myvolkswagen.de again changed the country accepted all the terms and now it works again.

**Comment by sebking1971** [comment]
Same here!

Sebastian King | ***@***.*** | +44 7711 702100
________________________________

**Comment by sebking1971** [comment]
stopped again with another error so guess VW are "doing stuff"

**Comment by geukster** [comment]
> logged in to myvolkswagen.de again changed the country accepted all the terms and now it works again.

Did the trick here too

**Comment by DarkFox** [comment]
> stopped again with another error so guess VW are "doing stuff"

Same here, with a different error message:

```
Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47
Integration: Volkswagen We Connect ID
First occurred: 00.12.00 (1 occurrences)
Last logged: 00.12.00

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided')
weconnect.errors.APICompatibilityError: No user id provided
```

**Comment by SwannyBFC** [comment]
> logged in to myvolkswagen.de again changed the country accepted all the terms and now it works again.

This worked for me on .co.uk and setting country to UK in the policy agreement, thanks

**Comment by sebking1971** [comment]
All good here now. One to remember for the future.

Sebastian King | ***@***.*** | +44 7711 702100
________________________________

**Comment by angelitoo776** [comment]
Same error here.

I finally solved. Ive tried the .de and .co.uk policy agreement and finally I went back to .es and works.
I don't know what really happened

**Comment by ColinRobbins** [comment]
I seem to have gotten over the "terms and conditions error but am now stuck with...

```weconnect.errors.APICompatibilityError: No user id provided```

Not sure where / how I can provide a user id?

**Comment by ColinRobbins** [comment]
Thanks @angelitoo776 - how did you repeat the login in HA.   
Did you remove the integration and re-add it?
I can't see any option to do it any other way?

**Comment by angelitoo776** [comment]
> Thanks @angelitoo776 - how did you repeat the login in HA.
> Did you remove the integration and re-add it?
> I can't see any option to do it any other way?

I removed the integration an re-add it. Unfortunately its a bit messy because you remove the entity id and you lose history data.

I think that you can try to reconnect the integration (it must appear a button to reconnect or something similar in the integration) if it doesn't work... re-add it

**Comment by ColinRobbins** [comment]
I've removed the integration, but now get an "unknown error" when I try to re-add it!
Similar error in the logs.
```
Logger: custom_components.volkswagen_we_connect_id.config_flow
Source: custom_components/volkswagen_we_connect_id/config_flow.py:39
Integration: Volkswagen We Connect ID
First occurred: 19:34:34 (1 occurrences)
Last logged: 19:34:34

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided')
weconnect.errors.APICompatibilityError: No user id provided
```

**Comment by northalpha** [comment]
I had both and resolved it by:

1. initial error: `You have to login at myvolkswagen.de and accept the terms and conditions`
--> go to myvolkswagen.de, login, accept the terms and conditions, done
2. new error: `No user id provided`
--> go to We Connect Shop, there i was again presented after login with new terms and conditions, accept it, done
3. i my case, for what ever reason, all "online" free services like "We Connect Plus", "We Connect" were not selected anymore. Bought all of them AGAIN (did it months ago ...) for 0€ and done.

Reload Integration and SoC et. al is back in my dashboard!

**Comment by ColinRobbins** [comment]
Thanks for the help but still no joy.

When I go to We Connect Shop, everything seems OK (www.volkswagen.co.uk/en/myvolkswagen.html)

![image](https://user-images.githubusercontent.com/13466873/219137952-960a9e3f-a4bd-47e0-bb36-0e10e480e405.png)

I am in the UK.
Did you specifically have to go to myvolkswagen.de?   I went to myvolkswagen.co.uk, as that is where my profile is registered.

Maybe I'll wait a few days (Sadly)
1) VW may fix something
2) At the weekend I can go to the upstream PyPi library and see if I can get that to logon there first.

Cheers

**Comment by ColinRobbins** [comment]
Fixed it.  In my case, the EV itself said I needed to re-logon.
So re did my login in the car, and now I can re-add the integration.
What a palaver!

**Comment by DarkFox** [comment]
I just logged into the danish Volkswagen site and got two terms to agree to, that didn't show up yesterday, and now it's working again. This is all very confusing.

**Comment by mitch-dc** [comment]
It's a mess right now. My car had 11 alerts that i need to relogin. After i just did that 😂

**Comment by torge70** [comment]
Tried to log in to myvokswagen.de and accept terms. Still not working for me.

2023-02-17 19:39:02.834 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry

**Comment by danros3** [comment]
Hi for me it's the same problem.
I tried to remove from Hassio integration and also the file from hacs (also file from custom_components)

After reboot of HA I have only...
![image](https://user-images.githubusercontent.com/69107406/219790849-d4833d86-966d-4617-a17e-2766bf9f8f61.png)

I wento to my car, into VW customers website: I din't undertsand were I need to accept...

Thank you very much

**Comment by koburg** [comment]
I got same error and never get it working not matter what I do.

it is either plugging version 1.3

or the new HA version which is broken this integration

**update**
i have tested 1.2 also same error

<img width="385" alt="image" src="https://user-images.githubusercontent.com/3473374/219868882-c059aab7-163c-4fc2-be4d-791042506b49.png">

**Comment by melstig** [comment]
I also tried to log in to myvokswagen.de and accept terms. Tried also the UK and Swedish sites. Still not working for me, cannot add the integration as I was quick to remove it.

Have not seen the mentioned prompt in the car yet.

2023-02-19 11:31:23.995 ERROR (MainThread) [custom_components.volkswagen_we_connect_id.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
info = await validate_input(self.hass, user_input)
File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
await hass.async_add_executor_job(we_connect.login)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
self.__session.login()
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
response = self.doWebAuth(authorizationUrl)
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth
raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions

**Comment by pansinmanteca** [comment]
Hello from Spain. 
After several tries, for me is working from myvolkswagen.de only. i have tried from .es .uk and no success.
Try from .de then accept all. Logout and then login again and accept all.
Keep the country Germany, restar HA and everything works fine.

**Comment by mitch-dc** [comment]
If you log out of the app, and then login again it should fix it as well.

**Comment by melstig** [comment]
After some more tries on https://vwid.vwgroup.io/account, switching between countries, logging out and in again and accepted the cookies on the site I managed to re-add the integration to Home Assistant. I also logged out and in in the Android App once. I did not have to login on the Infotainment screen but exactly what step that helped is unclear.

God luck to the rest of You that have problems!

**Comment by ChristianH21220** [comment]
> I'm getting a bit of a different error message. I did accept conditions, added country and restarted both HA, relogged in both we connect and HA without any luck:
> 
> File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login self.__session.login() File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize') File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl redirect = tryLoginResponse.headers['Location'] File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in **getitem** return self._store[key.lower()][1] KeyError: 'location'

Hi,
Same Error since today. Login at my Volkswagen and check if there was again something changed, but there is no change to see. Logout from the App at the Phone and restart HA did not help.

**Comment by gapthorpe** [comment]
This seems to be an issue with the backend python / VW API:
https://github.com/tillsteinbach/VWsFriend/issues/435

**Comment by jthun** [comment]
Same here. Was working fine until I restarted HA around 15:25 CET.

**Comment by ChristianH21220** [comment]
@gapthorpe : thx. That explain the issue, so we need wait that Till Steinbach check it.

**Comment by mitch-dc** [comment]
Let's wait. There is a big possibility that everything will magically work again. If not we need to wait for a fix in the WeConnect library :)

**Comment by PalmSwe** [comment]
I also have problems. Removed the integration and can't add it again. Error code below. Hope the integration will start to work soon again.

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by sebking1971** [comment]
From another integration someone has pointed out this

VW modified these URLs:
LOGIN_BASE = "https://emea.bff.cariad.digital/user-login/v1"
API_BASE = "https://emea.bff.cariad.digital/vehicle/v1"

And some other stuff maybe.

Broke TRONITY too but they have resolved.


Sebastian King | ***@***.*** | +44 7711 702100
________________________________

**Comment by davidwalton0** [comment]
I have the same "KeyError: 'location')" error report in HA. Haven't removed the integration though. Ohme charger stopped seeing the ID's SoC yesterday afternoon too. I've contacted Ohme with the details.

**Comment by mikrohard** [comment]
The weconnect library needs to be bumped to v0.54.1. But this causes dependancy conflicts with home assistant. I installed it manually and it seems to work (but I don't recommend this to anyone).

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. T
his behaviour is the source of the following dependency conflicts.                                          
nuheat 1.0.0 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.                 
ibm-watson 5.2.2 requires websocket-client==1.1.0, but you have websocket-client 1.5.1 which is incompatible
.                                                                                                           
homeassistant 2023.2.5 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.       
Successfully installed requests-2.28.2 weconnect-0.54.1`

**Comment by gmwubs** [comment]
> 

Well, for what it's worth: I did remove the custom integration, restarted home-assistant and then added the integration again. No luck so far, it keeps on failing on "KeyError: 'location' ".

**Comment by viddi87** [comment]
fix is up
https://github.com/tillsteinbach/WeConnect-python/releases/tag/v0.54.1

**Comment by jonas-wilnerzon** [comment]
Steinbach has released a fix now @ChristianH21220 @gapthorpe 
https://github.com/tillsteinbach/VWsFriend/releases/tag/v0.23.7

**Comment by mtjoernelund** [comment]
Had the same issue. Tried installing 1.1.4 that was just send out as pre-release. Now I get the following in the log: 
`Logger: homeassistant.util.package
Source: util/package.py:100 
First occurred: 13.51.10 (3 occurrences) 
Last logged: 13.51.13

Unable to install package weconnect==0.54.1: ERROR: Cannot install weconnect==0.54.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip `

**Comment by mvanninhuys** [comment]
just installed version V0.1.4 via hacs now i get this error ''Config-flow kon niet geladen worden: 500 Internal Server Error Server got itself in trouble'' anyone have an idea? version V0.1.3 i get one Unexpected error when I enter the username and password

**Comment by mtjoernelund** [comment]
> just installed version V0.1.4 via hacs now i get this error ''Config-flow kon niet geladen worden: 500 Internal Server Error Server got itself in trouble'' anyone have an idea? version V0.1.3 i get one Unexpected error when I enter the username and password

I get the same response with the error mentioned above in the log.

**Comment by mikrohard** [comment]
Just like I wrote above... this integration needs the newer version (0.54.1) of weconnect python library. But weconnect v0.54.1 depends on requests v2.28.2. Home assistant core depends on requests v2.28.1. Due to these dependancy conflicts it's impossible to resolve this properly right now. Home assistant core will need to bump the requests package dependancy.

You can manually install weconnect 0.54.1 (this will break some dependancies... but home assistant still works).

> pip install weconnect==0.54.1

**Comment by mtjoernelund** [comment]
> You can manually install weconnect 0.54.1 (this will break some dependancies... but home assistant still works).
> 
> > pip install weconnect==0.54.1
Did try a manual update of the weconnect package which allowed me to sign in again, and I did get some sensors. But Soc was still not available. Seems we need to wait for an update to HA Core.

**Comment by mitch-dc** [comment]
> Just like I wrote above... this integration needs the newer version (0.54.1) of weconnect python library. But weconnect v0.54.1 depends on requests v2.28.2. Home assistant core depends on requests v2.28.1. Due to these dependancy conflicts it's impossible to resolve this properly right now. Home assistant core will need to bump the requests package dependancy.
> 
> 
> 
> You can manually install weconnect 0.54.1 (this will break some dependancies... but home assistant still works).
> 
> 
> 
> > pip install weconnect==0.54.1

This is really helpfull. Thanks!

Maby we can PR the the version bump in HA.

**Comment by mitch-dc** [comment]
Opened an PR:
https://github.com/home-assistant/core/pull/88956

**Comment by gmwubs** [comment]
After installing the weconnect integration version 0.1.4, the integration didn´t work yet. Then I connected to the homeassistant container, did a pip install weconnect==0.54.1 and did another restart of homeassistant. The integration now partly works with a great number of sensors not working (see attached file).
[has_logs_vw_weconnnectid.log](https://github.com/mitch-dc/volkswagen_we_connect_id/files/10862397/has_logs_vw_weconnnectid.log)

**Comment by mitch-dc** [comment]
Fixed in https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.1.4 but you also need to 
update Homeassistant to at least version 2023.3.0.

**Comment by jonasbkarlsson** [comment]
I installed 2023.3.0, but it still has requests==2.28.1. Seems like the PR wasn't included in the 2023.3.0 release.

**Comment by jonas-wilnerzon** [comment]
@jonasbkarlsson It will probably be included in the april release of HA core.
https://github.com/home-assistant/core/pull/88956#issuecomment-1451347982

**Comment by mitch-dc** [comment]
My hope it is included in the .1 release

**Comment by ChristianH21220** [comment]
https://github.com/home-assistant/core/pull/88956#issuecomment-1451662705

Let's wait for .1

**Comment by viddi87** [comment]
> My hope it is included in the .1 release 

It's here 😀

**Comment by petosak** [comment]
Yes! Thank you very much @mitch-dc !!!!

**Comment by torge70** [comment]
Updated to 2023.3.1. Itegration still not working. Removed and added the integration.
Some sensors have appeared but not all. There are still errors.

Unexpected exception importing platform custom_components.volkswagen_we_connect_id.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/volkswagen_we_connect_id/sensor.py", line 100, in <module>
    device_class=SensorDeviceClass.energy,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: energy
