### ISSUE TITLE
WeConnect accounts with multiple cars (all of which not ID's)

### ISSUE THREAD

**Issue by odelma** [mitch-dc/volkswagen_we_connect_id#6]
First of all thanks for this great plugin, seems to work great! 👍 

**Is your feature request related to a problem? Please describe.**
Problem is that we have two cars on the WeConnect account and the other one is plain old combustion engine car. Some of the sensors for it are not valid.

**Describe the solution you'd like**
I would like to be able to choose the car(s) that I want to see with this integration. Or maybe it is possbile but I did not see a way to select the car, e.g. by VIN?

**Describe alternatives you've considered**
I would hope that the inegration would ask which cars to be included  as entities.

**Comment by mitch-dc** [comment]
Do the not-id cars use the weconnect-**id** app?

**Comment by odelma** [comment]
No there is a different WeConnect app. But in that app I can see my ID.3 - it just does not work through that. Both car are thus under the same account but there are some differences in the API they use…

**Comment by mitch-dc** [comment]
The focus of this integration is only ID cars, because these use a different API.

**Comment by odelma** [comment]
Yes, that is why I want to be able to exclude the combustion engine car. Currently I cannot do that (or I didn’t find a place where I could do it). So the combustion engine car is forcefully created as well and it actually makes the whole Raspberry Pi crash (running HA on Pi 3B+ in docker, not sure how this is possible even 😅). This happens a few minutes after startup. No more crashes after disabling this integration.

**Comment by mitch-dc** [comment]
Ahhh now i get what you mean. Hmm need to think about that.

**Comment by mitch-dc** [comment]
@odelma can you try the new beta:
https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.0.7-dev1

**Comment by odelma** [comment]
Thanks, happy to test it. I’ve installed current version via HACS, can I somehow upgrade through it as well or do I need to manually copy files?

**Comment by mitch-dc** [comment]
You can set hacs to import beta's. 
But i released a new version:
https://github.com/mitch-dc/volkswagen_we_connect_id/tree/v0.0.7.1

**Comment by odelma** [comment]
Thanks, had it enabled but didn't see first the -dev-version. I guess I  did not reload it. Now can see both. I did the update and HA does not create the entity for the diesel car. But in the logs I can still see this which ends to a crash of the whole system after few minutes:

```
homeassistant    | 2022-02-03 09:57:30 WARNING (SyncWorker_3) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:57:30 WARNING (SyncWorker_3) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:57:30 WARNING (SyncWorker_3) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:57:30 WARNING (SyncWorker_3) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
homeassistant    | 2022-02-03 09:57:39 WARNING (SyncWorker_3) [weconnect] Charging profiles are not yet implemented {'id': 1, 'name': 'Koti', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 100, 'options': {'autoUnlockPlugWhenCharged': 'off'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 2, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 3, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 4, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'singleTimer': {'occurringOn': 'Tuesday', 'startTime': '05:55'}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '05:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
homeassistant    | 2022-02-03 09:57:42 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:57:42 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:57:42 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:57:42 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
homeassistant    | 2022-02-03 09:57:51 WARNING (SyncWorker_8) [weconnect] Charging profiles are not yet implemented {'id': 1, 'name': 'Koti', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 100, 'options': {'autoUnlockPlugWhenCharged': 'off'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 2, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 3, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 4, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'singleTimer': {'occurringOn': 'Tuesday', 'startTime': '05:55'}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '05:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
homeassistant    | 2022-02-03 09:58:07 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:58:07 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:58:07 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:58:07 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
homeassistant    | 2022-02-03 09:58:16 WARNING (SyncWorker_1) [weconnect] Charging profiles are not yet implemented {'id': 1, 'name': 'Koti', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 100, 'options': {'autoUnlockPlugWhenCharged': 'off'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 2, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 3, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 4, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'singleTimer': {'occurringOn': 'Tuesday', 'startTime': '05:55'}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '05:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
homeassistant    | 2022-02-03 09:58:34 WARNING (SyncWorker_2) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:58:34 WARNING (SyncWorker_2) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:58:34 WARNING (SyncWorker_2) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:58:34 WARNING (SyncWorker_2) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
homeassistant    | 2022-02-03 09:58:43 WARNING (SyncWorker_2) [weconnect] Charging profiles are not yet implemented {'id': 1, 'name': 'Koti', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 100, 'options': {'autoUnlockPlugWhenCharged': 'off'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 2, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 3, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 4, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'singleTimer': {'occurringOn': 'Tuesday', 'startTime': '05:55'}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '05:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
homeassistant    | 2022-02-03 09:58:45 WARNING (SyncWorker_6) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:58:45 WARNING (SyncWorker_6) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:58:45 WARNING (SyncWorker_6) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:58:45 WARNING (SyncWorker_6) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
homeassistant    | 2022-02-03 09:58:54 WARNING (SyncWorker_6) [weconnect] Charging profiles are not yet implemented {'id': 1, 'name': 'Koti', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 100, 'options': {'autoUnlockPlugWhenCharged': 'off'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 2, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 3, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 4, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'singleTimer': {'occurringOn': 'Tuesday', 'startTime': '05:55'}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '05:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
homeassistant    | 2022-02-03 09:59:19 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:59:19 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:59:19 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:59:19 WARNING (SyncWorker_8) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
homeassistant    | 2022-02-03 09:59:27 WARNING (SyncWorker_8) [weconnect] Charging profiles are not yet implemented {'id': 1, 'name': 'Koti', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 100, 'options': {'autoUnlockPlugWhenCharged': 'off'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 2, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 3, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}, {'id': 4, 'enabled': False, 'startTime': '20:00', 'endTime': '04:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'singleTimer': {'occurringOn': 'Tuesday', 'startTime': '05:55'}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '05:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
homeassistant    | 2022-02-03 09:59:28 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/carType: An unsupported carType: diesel was provided, known values are [electric, hybrid, gasoline, petrol, cng, lpg, invalid, unknown car type] please report this as a bug
homeassistant    | 2022-02-03 09:59:28 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/fuelStatus/rangeStatus/primaryEngine/type: An unsupported type: diesel was provided, known values are [gasoline, electric, petrol, cng, lpg, invalid, unknown engine type] please report this as a bug
homeassistant    | 2022-02-03 09:59:28 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute adBlueRange with value 5500
homeassistant    | 2022-02-03 09:59:28 WARNING (SyncWorker_1) [weconnect] /vehicles/WVWZZZ3CZKEXYZXYZ/domains/measurements/rangeStatus: Unknown attribute dieselRange with value 870
```

**Comment by tillstaff** [comment]
> You can set hacs to import beta's. But i released a new version: https://github.com/mitch-dc/volkswagen_we_connect_id/tree/v0.0.7.1

Hello @mitch-dc,
Firstly, thanks for your integration!
I have two VW cars (Touran + ID3) and this new version is not working for me.
Here is the log error : 
```
2022-02-05 09:36:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 563, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/volkswagen_we_connect_id/binary_sensor.py", line 173, in is_on
    if isinstance(state.value, bool):
AttributeError: 'bool' object has no attribute 'value'
```
Do you need some other logs?

**Comment by tillstaff** [comment]
I just tested PR #14 and my electric car is now correctly added to home-assistant (without my other vehicule).
Thanks!

But I still have some log error : 
```
Logger: weconnect
Source: /usr/local/lib/python3.9/site-packages/weconnect/elements/generic_status.py:81
First occurred: 2:42:10 PM (36 occurrences)
Last logged: 2:47:08 PM

/vehicles/WVWZZZE1ZMP084008/domains/charging/chargingStatus: Unknown attribute chargeType with value invalid
/vehicles/WVWZZZE1ZMP084008/domains/charging/chargingStatus: Unknown attribute chargingSettings with value profile
```

**Comment by mitch-dc** [comment]
> I just tested PR #14 and my electric car is now correctly added to home-assistant (without my other vehicule).
> 
> Thanks!
> 
> 
> 
> But I still have some log error : 
> 
> ```
> 
> Logger: weconnect
> 
> Source: /usr/local/lib/python3.9/site-packages/weconnect/elements/generic_status.py:81
> 
> First occurred: 2:42:10 PM (36 occurrences)
> 
> Last logged: 2:47:08 PM
> 
> 
> 
> /vehicles/WVWZZZE1ZMP084008/domains/charging/chargingStatus: Unknown attribute chargeType with value invalid
> 
> /vehicles/WVWZZZE1ZMP084008/domains/charging/chargingStatus: Unknown attribute chargingSettings with value profile
> 
> ```

Great to hear the cars are added as expected. 

The new (warning) comes from the library that i use. Got the same warning and we need to wait untill the lib gets updated! I will post an issue on their github.
